import numpy as np

X_ENCASTREMENT1 = -0.1
Y_ENCASTREMENT1 = 0
POS_ENCASTREMENT1 = np.array([X_ENCASTREMENT1, Y_ENCASTREMENT1])

X_ENCASTREMENT2 = 0.1
Y_ENCASTREMENT2 = 0
POS_ENCASTREMENT2 = np.array([X_ENCASTREMENT2, Y_ENCASTREMENT2, np.pi])